name: century21test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter: 
    sdk: flutter
  dio: ^4.0.4
  lazy_load_scrollview: ^1.3.0
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  animate_do: ^2.1.0
  get_storage: ^2.0.3
  flutter_svg: ^1.0.3
  lottie: ^1.2.1

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/



